version: '3'
services:
  api:
    container_name: springboot-rest-api
    build:
      context: ./../
      dockerfile: .docker/Dockerfile
      target: dev
    environment:
      - DATABASE_DBNAME=${DATABASE_DBNAME:-bunny_books}
      - DATABASE_HOST=${DATABASE_HOST:-db}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-need-to-replace}
      - DATABASE_PORT=${DATABASE_PORT:-3306}
      - DATABASE_USER=${DATABASE_USER:-books}
      - FRONTEND_URL=${FRONTEND_URL-http://localhost:8080}
    platform: linux/x86_64
    ports:
      - "9000:9000"
    volumes:
      - ./../:/app
  db:
    container_name: springboot-rest-db
    image: mysql:8.0.32
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db-data:/var/lib/mysql:delegated
    environment:
      - MYSQL_DATABASE=bunny_books
      - MYSQL_PASSWORD=need-to-replace
      - MYSQL_ROOT_PASSWORD=need-to-replace
      - MYSQL_USER=books
    expose:
      - 3306
    ports:
      - "3006:3006"
volumes:
  db-data:
